# backend/Dockerfile
FROM golang:1.22-alpine AS builder

WORKDIR /

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o api ./cmd/api

FROM alpine:3.19

WORKDIR /

COPY --from=builder /api .

EXPOSE 8080

CMD ["./api"]
