# Etapa 1: Build do React
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: Servir o build via Nginx
FROM nginx:alpine

# Copia o build do React para a pasta padrão do Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copia nginx.conf customizado
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]